name: Publish to Central

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          settings-path: ~ # location for the settings.xml file

      - name: Build and publish
        run: |
          set -e
          revision=${GITHUB_REF##*/}
          echo "Publishing version $revision to Central"
          echo ${{ secrets.GPG_SECRETKEYS }} | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
          echo ${{ secrets.GPG_OWNERTRUST }} | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes
          mvn -Prelease -B deploy -s $GITHUB_WORKSPACE/settings.xml -Drevision=$revision -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_EXECUTABLE: gpg
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
